Update dev dependency phpunit to 10 and 11
123inkt/phpunit-file-coverage-inspection pull request #42
Opened 2024-06-14 09:54 UTC by anne-gaelle123inkt

2024-06-14 12:07 UTC, bram123 requested changes

2024-06-14 12:07 UTC, bram123 commented on .github/workflows/test.yml
> +          - symfony: '^7.0'
Also remove the exclude symfony.
Before it was skipping the combination of symfony 7.0 with php 8.1. Now it's fully skipping symfony 7.0

2024-06-17 09:01 UTC, anne-gaelle123inkt commented on .github/workflows/test.yml
> +          - symfony: '^7.0'
Our internal repositories are still using 8.1, so I put back the compatibility with 8.1

2024-06-17 12:47 UTC, bram123 requested changes

2024-06-18 09:19 UTC, anne-gaelle123inkt commented on composer.json
> +        "php": ">=8.1 || >=8.2",
yes fixed

2024-06-18 09:47 UTC, bram123 approved these changes

2024-06-18 10:20 UTC, merged