Add gitlab error renderer
123inkt/phpunit-file-coverage-inspection pull request #8
Opened 2021-08-04 19:04 UTC by frankdekker

Feature: add gitlab error renderer format

Added new renderer for gitlab format
Added new cli option --report. Options `checkstyle|gitlab`, defaults to checkstyle.
Added coverage

2021-08-04 19:07 UTC, frankdekker commented
@daanheikens 
You're up, phpfci done :)

2021-08-04 19:57 UTC, bram123 requested changes

2021-08-04 19:57 UTC, bram123 commented on phpunit.xml.dist
> +         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.5/phpunit.xsd"
Can you then also update composer.json to "^9.5" ?

2021-08-04 20:33 UTC, frankdekker commented on phpunit.xml.dist
> +         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.5/phpunit.xsd"
Odd, had removed 8.5, was default 9.4 then. Now changed to ^9.5

2021-08-05 05:11 UTC, daanheikens approved these changes
Looking good to me!

2021-08-05 07:49 UTC, bram123 approved these changes

2021-08-05 19:47 UTC, merged